title: Life in Argentina
description: Legal and relocation support for people moving to Argentina.
url: https://lifeinargentina.com
baseurl: ""
timezone: America/Argentina/Buenos_Aires

permalink: /blog/:title/

markdown: kramdown

exclude:
  - README.md
